apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rnxdknjvs-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-889492a693.0jv5.p3.openshiftapps.com/rhtap/rhtap-qe:1fcb1f86bad0612b093a33d70bc629f3a1b49f8b@sha256:b070ee3c5f902509f9bc90aaed0ef69f9383910eb1d4c676668d4b2d82e2036c
          name: container-image
