apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rnxdknjvs-python 
  janus-idp.io/tekton: rnxdknjvs-python
  backstage.io/kubernetes-id: rnxdknjvs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rnxdknjvs-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  